CommunityCares_Web/Models/Collect.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommunityCares_Web.Models;

[Table("Collect")]
public partial class Collect
{
    [Key]
    public int Id { get; set; }

    [Column("date", TypeName = "datetime")]
    public DateTime Date { get; set; }

    [Column("idCampaign")]
    public int IdCampaign { get; set; }

    [ForeignKey("IdCampaign")]
    [InverseProperty("Collects")]
    public virtual Campaign? IdCampaignNavigation { get; set; } = null!;
    public virtual ICollection<Donation> Donations { get; set; } = new List<Donation>();
}

CommunityCares_Web/Controllers/CollectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CommunityCares_Web.Data;
using CommunityCares_Web.Models;

namespace CommunityCares_Web.Controllers
{
    public class CollectController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CollectController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Collect
        public async Task<IActionResult> Index(int id)
        {
            var applicationDbContext = _context.Collects.Include(c => c.IdCampaignNavigation).Where(x =>x.IdCampaign ==id);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Collect/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Collects == null)
            {
                return NotFound();
            }

            var collect = await _context.Collects
                .Include(c => c.IdCampaignNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (collect == null)
            {
                return NotFound();
            }

            return View(collect);
        }

        // GET: Collect/Create
        public IActionResult Create()
        {
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id");
            return View();
        }

        // POST: Collect/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id,[Bind("Date,IdCampaign")] Collect collect)
        {
            if (ModelState.IsValid)
            {
                collect.IdCampaign = id;
                _context.Add(collect);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id", collect.IdCampaign);
            return View(collect);
        }

        // GET: Collect/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Collects == null)
            {
                return NotFound();
            }

            var collect = await _context.Collects.FindAsync(id);
            if (collect == null)
            {
                return NotFound();
            }
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id", collect.IdCampaign);
            return View(collect);
        }

        // POST: Collect/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,IdCampaign")] Collect collect)
        {
            if (id != collect.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(collect);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CollectExists(collect.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id", collect.IdCampaign);
            return View(collect);
        }

        // GET: Collect/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Collects == null)
            {
                return NotFound();
            }

            var collect = await _context.Collects
                .Include(c => c.IdCampaignNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (collect == null)
            {
                return NotFound();
            }

            return View(collect);
        }

        // POST: Collect/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Collects == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Collects'  is null.");
            }
            var collect = await _context.Collects.FindAsync(id);
            if (collect != null)
            {
                _context.Collects.Remove(collect);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CollectExists(int id)
        {
          return (_context.Collects?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CommunityCares_Web/Controllers/DonationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CommunityCares_Web.Data;
using CommunityCares_Web.Models;
using System.Net.Mail;
using System.Net;

namespace CommunityCares_Web.Controllers
{
    public class DonationController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DonationController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Donation
        public async Task<IActionResult> Index()
        {
            return _context.Donations != null ?
                       View(await _context.Donations.ToListAsync()) :
                       Problem("Entity set 'TopServiceBDOContext.CustomerUser'  is null.");
        }

        public IActionResult Index2(int id)
        {
           var don = from dona in _context.Donations.Include(a => a.IdDonnorsNavigation).Include(a => a.IdDonnorsNavigation.IdNavigation).Include(a => a.IdCampaignNavigation.IdAssylumNavigation)
                                             
                                             where dona.IdCampaign == id
                                             select dona;


            return View(don.ToList());
        }

        public IActionResult Index3(int id)
        {
            var don = from dona in _context.Donations.Include(a => a.IdDonnorsNavigation).Include(a => a.IdDonnorsNavigation.IdNavigation).Include(a => a.IdCampaignNavigation.IdAssylumNavigation)

                      where dona.IdCollect == id
                      orderby dona.Hour
                      select dona;


            return View(don.ToList());
        }

        public IActionResult DonacionesRecibidas(int id)
        {
            var don = from dona in _context.Donations.Include(a => a.IdDonnorsNavigation).Include(a => a.IdDonnorsNavigation.IdNavigation).Include(a => a.IdCampaignNavigation.IdAssylumNavigation)
                     
                      where dona.IdCampaign == id && dona.IsReceived == "Y"
                     
                      select dona;


            return View(don.ToList());
        }

        public IActionResult ConfirmarDonacion(int id)
        {
            var don = from dona in _context.Donations.Include(a => a.IdDonnorsNavigation).Include(a => a.IdDonnorsNavigation.IdNavigation).Include(a => a.IdCampaignNavigation.IdAssylumNavigation)

                      where dona.IdCampaign == id && dona.IsReceived == "N"
                      select dona;


            return View(don.ToList());
        }

        // GET: Donation/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Donations == null)
            {
                return NotFound();
            }

            var donation = await _context.Donations
                .Include(d => d.IdCampaignNavigation)
                .Include(d => d.IdCollectsNavigation)
                .Include(d => d.IdDonnorsNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (donation == null)
            {
                return NotFound();
            }

            return View(donation);
        }

        // GET: Donation/Create
        public IActionResult Create(int id)
        {
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id");
            ViewData["IdCollect"] = new SelectList(_context.Collects.Where(x=>x.Id == id), "Id", "Date");
            ViewData["IdDonnors"] = new SelectList(_context.Donors, "Id", "Id");
            return View();
        }

        // POST: Donation/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id,[Bind("DescriptionItems,DescriptionMonto,Status,RegisterDate,IsAnonymus,IsReceived,IdCollect,Hour,IdCampaign,IdDonnors")] Donation donation)
        {
            if (ModelState.IsValid)
            {
                donation.IsReceived = "N";
                donation.IdDonnors = SessionClass.Id;
                donation.IdCampaign = id;
                donation.RegisterDate = DateTime.Now;
                _context.Add(donation);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index2", "Campaign");
            }
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id", donation.IdCampaign);
            ViewData["IdCollect"] = new SelectList(_context.Collects, "Id", "Date", donation.IdCollect);
            ViewData["IdDonnors"] = new SelectList(_context.Donors, "Id", "Id", donation.IdDonnors);
            return RedirectToAction("Index2", "Campaign");
        }

        // GET: Donation/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Donations == null)
            {
                return NotFound();
            }

            var donation = await _context.Donations.FindAsync(id);
            if (donation == null)
            {
                return NotFound();
            }
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id", donation.IdCampaign);
            ViewData["IdCollect"] = new SelectList(_context.Collects, "Id", "Id", donation.IdCollect);
            ViewData["IdDonnors"] = new SelectList(_context.Donors, "Id", "Id", donation.IdDonnors);
            return View(donation);
        }

        // POST: Donation/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,DescriptionItems,DescriptionMonto,Status,RegisterDate,IsAnonymus,IsReceived,IdCollect,Hour,IdCampaign,IdDonnors")] Donation donation)
        {
            if (id != donation.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(donation);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DonationExists(donation.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id", donation.IdCampaign);
            ViewData["IdCollect"] = new SelectList(_context.Collects, "Id", "Id", donation.IdCollect);
            ViewData["IdDonnors"] = new SelectList(_context.Donors, "Id", "Id", donation.IdDonnors);
            return View(donation);
        }

        //Metodo Para confirmar el recibo de la donacion
        

        public async Task<IActionResult> ConfirmarRecibo(int id)
        {

            var camp = await _context.Donations.FirstAsync(x => x.Id == id);
            var ID = await _context.Donations.FirstAsync(x => x.Id == id);
            var idCap = ID.IdDonnors;
            var user = await _context.Users.FirstOrDefaultAsync(x => x.Id == idCap);

            camp.IsReceived = "Y";
            _context.Update(camp);
            await _context.SaveChangesAsync();


            EnviarCorreo(user.Email,"Des","cuerpo");



            return RedirectToAction("Index", "Campaign", new { id = ID.IdCampaign });
        }

        public void EnviarCorreo(string destinatario, string asunto, string cuerpo)
        {
            try
            {
                // Configurar el cliente SMTP
                SmtpClient clienteSmtp = new SmtpClient("smtp.gmail.com");
                clienteSmtp.Port = 587;
                clienteSmtp.EnableSsl = true;
                clienteSmtp.UseDefaultCredentials = false;
                clienteSmtp.Credentials = new NetworkCredential("rolycgr12@gmail.com", "iibbjmekeeoltgpv");

                // Crear el mensaje de correo
                MailMessage mensaje = new MailMessage();
                mensaje.From = new MailAddress("rolycgr12@gmail.com");
                mensaje.To.Add(destinatario);
                mensaje.Subject = asunto;
                mensaje.Body = cuerpo;

                // Enviar el correo
                clienteSmtp.Send(mensaje);
            }
            catch (Exception ex)
            {
                // Manejar cualquier error que pueda ocurrir durante el envío del correo
                Console.WriteLine("Error al enviar el correo: " + ex.Message);
            }
        }

        // GET: Donation/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Donations == null)
            {
                return NotFound();
            }

            var donation = await _context.Donations
                .Include(d => d.IdCampaignNavigation)
                .Include(d => d.IdCollectsNavigation)
                .Include(d => d.IdDonnorsNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (donation == null)
            {
                return NotFound();
            }

            return View(donation);
        }

        // POST: Donation/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Donations == null)
            {

CommunityCares_Web/Views/Collect/Create.cshtml
@model CommunityCares_Web.Models.Collect

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Collect</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CommunityCares_Web/Views/Collect/Delete.cshtml
@model CommunityCares_Web.Models.Collect

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Collect</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCampaignNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCampaignNavigation.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CommunityCares_Web/Views/Collect/Details.cshtml
@model CommunityCares_Web.Models.Collect

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Collect</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdCampaignNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdCampaignNavigation.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CommunityCares_Web/Views/Collect/Edit.cshtml
@model CommunityCares_Web.Models.Collect

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Collect</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCampaign" class="control-label"></label>
                <select asp-for="IdCampaign" class="form-control" asp-items="ViewBag.IdCampaign"></select>
                <span asp-validation-for="IdCampaign" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CommunityCares_Web/Views/Collect/Index.cshtml
@model IEnumerable<CommunityCares_Web.Models.Collect>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdCampaignNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IdCampaignNavigation.Name)
            </td>
            <td>
                <a asp-action="Index3" asp-controller="Donation" asp-route-id="@item.Id">Ver Donaciones para esta fecha</a> |
                
            </td>
        </tr>
}
    </tbody>
</table>