CommunityCares_Web/Models/Campaign.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommunityCares_Web.Models;

[Table("Campaign")]
public partial class Campaign
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string? Name { get; set; } 

    [StringLength(50)]
    [Unicode(false)]
    public string? Requirement { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime InitialDate { get; set; }= DateTime.Now;

    [Column(TypeName = "datetime")]
    public DateTime CloseDate { get; set; }=DateTime.Now;

    public byte Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RegisterDate { get; set; }

    public byte IdAssylum { get; set; }

    [InverseProperty("IdCampaignNavigation")]
    public virtual ICollection<Collect> Collects { get; set; } = new List<Collect>();

   
    public virtual ICollection<Donation> Donations { get; set; } = new List<Donation>();

    [ForeignKey("IdAssylum")]
    [InverseProperty("Campaigns")]
    public virtual Assylum? IdAssylumNavigation { get; set; } = null!;

    [InverseProperty("IdCampaignNavigation")]
    public virtual ICollection<Image> Images { get; set; } = new List<Image>();
}

CommunityCares_Web/Controllers/CollectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CommunityCares_Web.Data;
using CommunityCares_Web.Models;

namespace CommunityCares_Web.Controllers
{
    public class CollectController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CollectController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Collect
        public async Task<IActionResult> Index(int id)
        {
            var applicationDbContext = _context.Collects.Include(c => c.IdCampaignNavigation).Where(x =>x.IdCampaign ==id);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Collect/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Collects == null)
            {
                return NotFound();
            }

            var collect = await _context.Collects
                .Include(c => c.IdCampaignNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (collect == null)
            {
                return NotFound();
            }

            return View(collect);
        }

        // GET: Collect/Create
        public IActionResult Create()
        {
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id");
            return View();
        }

        // POST: Collect/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id,[Bind("Date,IdCampaign")] Collect collect)
        {
            if (ModelState.IsValid)
            {
                collect.IdCampaign = id;
                _context.Add(collect);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id", collect.IdCampaign);
            return View(collect);
        }

        // GET: Collect/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Collects == null)
            {
                return NotFound();
            }

            var collect = await _context.Collects.FindAsync(id);
            if (collect == null)
            {
                return NotFound();
            }
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id", collect.IdCampaign);
            return View(collect);
        }

        // POST: Collect/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Date,IdCampaign")] Collect collect)
        {
            if (id != collect.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(collect);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CollectExists(collect.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id", collect.IdCampaign);
            return View(collect);
        }

        // GET: Collect/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Collects == null)
            {
                return NotFound();
            }

            var collect = await _context.Collects
                .Include(c => c.IdCampaignNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (collect == null)
            {
                return NotFound();
            }

            return View(collect);
        }

        // POST: Collect/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Collects == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Collects'  is null.");
            }
            var collect = await _context.Collects.FindAsync(id);
            if (collect != null)
            {
                _context.Collects.Remove(collect);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CollectExists(int id)
        {
          return (_context.Collects?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CommunityCares_Web/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CommunityCares_Web.Data;
using CommunityCares_Web.Models;

using Firebase.Storage;

using System.Text;
using Firebase.Auth;

namespace CommunityCares_Web.Controllers
{
    public class ImageController : Controller
    {
        private static string ApiKey = "AIzaSyA4DjsG7hKblkmS8RO9JluoKCS4Gk_y_f8";
        private static string Bucket = "taskmanager-62211.appspot.com";
        private static string AuthEmail = "apalamarcelo@gmail.com";
        private static string AuthPassword = "Admin_123";
        private readonly ApplicationDbContext _context;

        public ImageController(ApplicationDbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index(int id)
        {
            IQueryable<Image> image = from imag in _context.Images.Include(a => a.IdCampaignNavigation).Include(x=>x.IdCampaignNavigation.IdAssylumNavigation)
                                             
                                             where imag.IdCampaign == id
                                             select imag;


            return View(image.ToList());
        }
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Images == null)
            {
                return NotFound();
            }

            var image = await _context.Images
                .Include(i => i.IdCampaignNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }
        private static async Task<string> SubirImagen(IFormFile file)
        {
            if (file != null && file.Length > 0)
            {
                // Autenticación con Firebase
                var auth = new FirebaseAuthProvider(new FirebaseConfig(ApiKey));

                var authResult = await auth.SignInWithEmailAndPasswordAsync(AuthEmail, AuthPassword);

                // Crear instancia de FirebaseStorage
                var storage = new FirebaseStorage(
                    Bucket,
                    new FirebaseStorageOptions
                    {
                        AuthTokenAsyncFactory = () => Task.FromResult(authResult.FirebaseToken),
                        ThrowOnCancel = true // Cuando se cancela la carga, se lanza una excepción. Por defecto, no se lanza ninguna excepción.
                    });

                // Ruta en la que deseas almacenar la imagen en Firebase Storage
                string storagePath = file.FileName;

                // Subir la imagen a Firebase Storage
                using (var stream = file.OpenReadStream())
                {
                    var task = storage.Child(storagePath).PutAsync(stream);
                    try
                    {
                        // Obtener la URL de descarga de la imagen
                        var downloadUrl = await task;

                        // Retornar la URL de descarga de la imagen
                        return downloadUrl;
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine(ex.ToString());
                    }
                }
            }

            return null; // Si no se pudo subir la imagen, retorna null
        }
        public IActionResult Create()
        {
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Name");
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(int id,[Bind("Url,IdCampaign")] Image image, IFormFile file)
        {
            if (ModelState.IsValid)
            {

               
                
                // Aquí llamas al método para subir la imagen a Firebase Storage
                var imageUrl = await SubirImagen(file);

                // Asignar la URL de descarga de la imagen al campo Url del modelo Image
                image.Url = imageUrl;

                // Resto del código para guardar el modelo en la base de datos
                image.IdCampaign = id;
                _context.Add(image);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id", image.IdCampaign);
            return RedirectToAction("Index" , "Campaign");
        }
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Images == null)
            {
                return NotFound();
            }

            var image = await _context.Images.FindAsync(id);
            if (image == null)
            {
                return NotFound();
            }
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id", image.IdCampaign);
            return View(image);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Url,IdCampaign")] Image image)
        {
            if (id != image.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(image);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImageExists(image.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCampaign"] = new SelectList(_context.Campaigns, "Id", "Id", image.IdCampaign);
            return View(image);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Images == null)
            {
                return NotFound();
            }

            var image = await _context.Images
                .Include(i => i.IdCampaignNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (image == null)
            {
                return NotFound();
            }

            return View(image);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Images == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Images'  is null.");
            }
            var image = await _context.Images.FindAsync(id);
            if (image != null)
            {
                _context.Images.Remove(image);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ImageExists(int id)
        {
          return (_context.Images?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CommunityCares_Web/Views/Campaign/Create.cshtml
@model CommunityCares_Web.Models.Campaign

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Campaign</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Requirement" class="control-label"></label>
                <input asp-for="Requirement" class="form-control" />
                <span asp-validation-for="Requirement" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InitialDate" class="control-label"></label>
                <input asp-for="InitialDate" class="form-control" />
                <span asp-validation-for="InitialDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CloseDate" class="control-label"></label>
                <input asp-for="CloseDate" class="form-control" />
                <span asp-validation-for="CloseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" value="1" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>


            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CommunityCares_Web/Views/Campaign/Delete.cshtml
@model CommunityCares_Web.Models.Campaign

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Campaign</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Requirement)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Requirement)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InitialDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InitialDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CloseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CloseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdAssylumNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdAssylumNavigation.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CommunityCares_Web/Views/Campaign/Details.cshtml
@model CommunityCares_Web.Models.Campaign

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Campaign</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Requirement)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Requirement)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.InitialDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.InitialDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CloseDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CloseDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdAssylumNavigation)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdAssylumNavigation.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CommunityCares_Web/Views/Campaign/Edit.cshtml
@model CommunityCares_Web.Models.Campaign

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Campaign</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Requirement" class="control-label"></label>
                <input asp-for="Requirement" class="form-control" />
                <span asp-validation-for="Requirement" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="InitialDate" class="control-label"></label>
                <input asp-for="InitialDate" class="form-control" />
                <span asp-validation-for="InitialDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CloseDate" class="control-label"></label>
                <input asp-for="CloseDate" class="form-control" />
                <span asp-validation-for="CloseDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegisterDate" class="control-label"></label>
                <input asp-for="RegisterDate" class="form-control" />
                <span asp-validation-for="RegisterDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdAssylum" class="control-label"></label>
                <select asp-for="IdAssylum" class="form-control" asp-items="ViewBag.IdAssylum"></select>
                <span asp-validation-for="IdAssylum" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CommunityCares_Web/Views/Campaign/Edit2.cshtml
@model CommunityCares_Web.Models.Campaign

@{
    ViewData["Title"] = "Edit";
}

<h1>Seguro de cerrar campaña??</h1>

<h4>Campaign</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit2">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

CommunityCares_Web/Views/Campaign/Index.cshtml
@model IEnumerable<CommunityCares_Web.Models.Campaign>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Requirement)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InitialDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CloseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegisterDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdAssylumNavigation)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Requirement)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InitialDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CloseDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RegisterDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdAssylumNavigation.Id)
                </td>
                <td>
                    <a asp-action="Create" asp-controller="Image" asp-route-id="@item.Id">Agrear Imagenes</a><br>
                    <a asp-action="Index" asp-controller="Image" asp-route-id="@item.Id">Ver mas Informacion</a><br>
                    <a asp-action="Create" asp-controller="Collect" asp-route-id="@item.Id">Definir fecha de recojo</a> <br>
                    <a asp-action="Index" asp-controller="Collect" asp-route-id="@item.Id">Ver Fechas de Recojo</a><br>
                    <a asp-area="" asp-controller="Donation" asp-route-id="@item.Id" asp-action="ConfirmarDonacion">Ver Donaciones Pendientes</a><br>
                    <a asp-area="" asp-controller="Donation" asp-route-id="@item.Id" asp-action="DonacionesRecibidas">Donaciones Recibidas</a><br>
                   
                    <a asp-action="Edit2"  asp-route-id="@item.Id">Cerrar Campaña</a>|
                   
                </td>
            </tr>
        }
    </tbody>
</table>

CommunityCares_Web/Views/Campaign/Index2.cshtml
@model IEnumerable<CommunityCares_Web.Models.Campaign>
<br />
<h1 class="text-uppercase">Campañas Vigentes</h1>
<br />

<div class="row row-cols-1 row-cols-md-2 g-4">
    @foreach (var item in Model)
    {
        <div class="col">
            <div class="card text-center" style="width: 18rem;">
                <div class="card-body">
                    <h2 class="card-title">@item.IdAssylumNavigation.Name</h2>
                    <p class="card-text">Requerimientos: @item.Name</p>
                    <p class="card-text">Requerimientos: @item.Requirement</p>
                    <p class="card-text">Fehca de cierre: @item.CloseDate</p>
                    

                    <a asp-action="Index" asp-controller="Image" asp-route-id="@item.Id" class="btn btn-primary">Ver Informacion</a>
                    <a asp-action="Create" asp-controller="Donation" asp-route-id="@item.Id" class="btn btn-primary">Donar</a>
                </div>
            </div>
        </div>
    }
</div>

CommunityCares_Web/Views/Campaign/Index3.cshtml
@model IEnumerable<CommunityCares_Web.Models.Campaign>
<br />
<h1 class="text-uppercase">Campañas Cerradas</h1>
<br />

<div class="row row-cols-1 row-cols-md-2 g-4">
    @foreach (var item in Model)
    {
        <div class="col">
            <div class="card text-center" style="width: 18rem;">
                <div class="card-body">
                    <h2 class="card-title">@item.IdAssylumNavigation.Name</h2>
                    <p class="card-text">Requerimientos: @item.Name</p>
                    <p class="card-text">Requerimientos: @item.Requirement</p>
                    <p class="card-text">Fehca de cierre: @item.CloseDate</p>
                    

                    <a asp-action="Index" asp-controller="Image" asp-route-id="@item.Id" class="btn btn-primary">Ver Informacion</a>
                    <a asp-action="Index2" asp-controller="Donation" asp-route-id="@item.Id" class="btn btn-primary">Ver Donaciones</a>
                    <a class="btn btn-Danger">Cerrada</a>
                </div>
            </div>
        </div>
    }
</div>