CommunityCares_Web/Models/Assylum.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace CommunityCares_Web.Models;

[Table("Assylum")]
public partial class Assylum
{
    [Key]
    public byte Id { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; } = null!;

    [StringLength(50)]
    [Unicode(false)]
    public string Nit { get; set; } = null!;

    [StringLength(50)]
    [Unicode(false)]
    public string RepresentativeName { get; set; } = null!;

    [StringLength(150)]
    [Unicode(false)]
    public string BussinessEmail { get; set; } = null!;

    [StringLength(50)]
    [Unicode(false)]
    public string CellphoneNumber { get; set; } = null!;

    [StringLength(150)]
    [Unicode(false)]
    public string Address { get; set; } = null!;

    [Column("latitude")]
    public double Latitude { get; set; }

    [Column("longitude")]
    public double Longitude { get; set; }

    [Column("status")]
    public byte Status { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime RegisterDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string Region { get; set; } = null!;

    [InverseProperty("IdAssylumNavigation")]
    public virtual ICollection<Admin> Admins { get; set; } = new List<Admin>();

    [InverseProperty("IdAssylumNavigation")]
    public virtual ICollection<Campaign> Campaigns { get; set; } = new List<Campaign>();
}

CommunityCares_Web/Controllers/AssylumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CommunityCares_Web.Data;
using CommunityCares_Web.Models;
using Microsoft.AspNetCore.Authorization;

namespace CommunityCares_Web.Controllers
{
    public class AssylumController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AssylumController(ApplicationDbContext context)
        {
            _context = context;
        }
        //[Authorize(Roles ="Admin")]
        // GET: Assylum
        public async Task<IActionResult> Index()
        {
            var assylum = _context.Assylums.Where(x => x.Status == 1);
            return View(assylum.ToList());
        }

        // GET: Assylum/Details/5
        public async Task<IActionResult> Details(byte? id)
        {
            if (id == null || _context.Assylums == null)
            {
                return NotFound();
            }

            var assylum = await _context.Assylums
                .FirstOrDefaultAsync(m => m.Id == id);
            if (assylum == null)
            {
                return NotFound();
            }

            return View(assylum);
        }

        // GET: Assylum/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Assylum/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,Nit,RepresentativeName,BussinessEmail,CellphoneNumber,Address,Latitude,Longitude,Status,RegisterDate,Region")] Assylum assylum)
        {
            if (ModelState.IsValid)
            {
                assylum.RegisterDate = DateTime.Now;
                _context.Add(assylum);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(assylum);
        }

        // GET: Assylum/Edit/5
        public async Task<IActionResult> Edit(byte? id)
        {
            if (id == null || _context.Assylums == null)
            {
                return NotFound();
            }

            var assylum = await _context.Assylums.FindAsync(id);
            if (assylum == null)
            {
                return NotFound();
            }
            return View(assylum);
        }

        // POST: Assylum/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(byte id, [Bind("Id,Name,Nit,RepresentativeName,BussinessEmail,CellphoneNumber,Address,Latitude,Longitude,Status,RegisterDate,Region")] Assylum assylum)
        {
            if (id != assylum.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(assylum);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AssylumExists(assylum.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(assylum);
        }

        // GET: Assylum/Delete/5
        public async Task<IActionResult> Delete(byte? id)
        {
            if (id == null || _context.Assylums == null)
            {
                return NotFound();
            }

            var assylum = await _context.Assylums
                .FirstOrDefaultAsync(m => m.Id == id);
            if (assylum == null)
            {
                return NotFound();
            }

            return View(assylum);
        }

        // POST: Assylum/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(byte id)
        {
            if (_context.Assylums == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Assylums'  is null.");
            }
            var assylum = await _context.Assylums.FindAsync(id);
            if (assylum != null)
            {
                _context.Assylums.Remove(assylum);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AssylumExists(byte id)
        {
          return (_context.Assylums?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CommunityCares_Web/Controllers/CampaignController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CommunityCares_Web.Data;
using CommunityCares_Web.Models;

namespace CommunityCares_Web.Controllers
{
    public class CampaignController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CampaignController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Campaign
        public async Task<IActionResult> Index(int id)
        {
            var Campaign = _context.Campaigns.Where(x => x.Status == 1).Where(x => x.IdAssylum == id);
            return View(Campaign.ToList());
        }

        public async Task<IActionResult> Index2()
        {
            var Campaign = _context.Campaigns.Include(x=>x.IdAssylumNavigation).Where(x => x.Status == 1);
            return View(Campaign.ToList());
        }
        public async Task<IActionResult> Index3()
        {
            var Campaign = _context.Campaigns.Include(x => x.IdAssylumNavigation).Where(x => x.Status == 2);
            return View(Campaign.ToList());
        }

        // GET: Campaign/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Campaigns == null)
            {
                return NotFound();
            }

            var campaign = await _context.Campaigns
                .Include(c => c.IdAssylumNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (campaign == null)
            {
                return NotFound();
            }

            return View(campaign);
        }

        // GET: Campaign/Create
        public IActionResult Create()
        {
            ViewData["IdAssylum"] = new SelectList(_context.Assylums, "Id", "Id");
            return View();
        }

        // POST: Campaign/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(byte id,[Bind("Name,Requirement,InitialDate,CloseDate,Status,RegisterDate,IdAssylum")] Campaign campaign)
        {
            if (ModelState.IsValid)
            {
                campaign.RegisterDate = DateTime.Now;
                campaign.IdAssylum = id;
                _context.Add(campaign);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdAssylum"] = new SelectList(_context.Assylums, "Id", "Id", campaign.IdAssylum);
            return View(campaign);
        }

        // GET: Campaign/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Campaigns == null)
            {
                return NotFound();
            }

            var campaign = await _context.Campaigns.FindAsync(id);
            if (campaign == null)
            {
                return NotFound();
            }
            ViewData["IdAssylum"] = new SelectList(_context.Assylums, "Id", "Id", campaign.IdAssylum);
            return View(campaign);
        }

        // POST: Campaign/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Requirement,InitialDate,CloseDate,Status,RegisterDate,IdAssylum")] Campaign campaign)
        {
            if (id != campaign.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(campaign);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CampaignExists(campaign.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdAssylum"] = new SelectList(_context.Assylums, "Id", "Id", campaign.IdAssylum);
            return View(campaign);
        }



        // GET: Campaign/Edit/5
        public async Task<IActionResult> Edit2(int? id)
        {
            if (id == null || _context.Campaigns == null)
            {
                return NotFound();
            }

            var campaign = await _context.Campaigns.FindAsync(id);
            if (campaign == null)
            {
                return NotFound();
            }
            ViewData["IdAssylum"] = new SelectList(_context.Assylums, "Id", "Id", campaign.IdAssylum);
            return View(campaign);
        }

        // POST: Campaign/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit2(int id)
        {

            var camp = await _context.Campaigns.FirstAsync(x => x.Id == id);

            camp.Status = 2;
            _context.Update(camp);
            await _context.SaveChangesAsync();





           
            return RedirectToAction("Index" , "Assylum");
        }
        // GET: Campaign/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Campaigns == null)
            {
                return NotFound();
            }

            var campaign = await _context.Campaigns
                .Include(c => c.IdAssylumNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (campaign == null)
            {
                return NotFound();
            }

            return View(campaign);
        }

        // POST: Campaign/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Campaigns == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Campaigns'  is null.");
            }
            var campaign = await _context.Campaigns.FindAsync(id);
            if (campaign != null)
            {
                _context.Campaigns.Remove(campaign);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CampaignExists(int id)
        {
          return (_context.Campaigns?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

CommunityCares_Web/Views/Assylum/Create.cshtml
@model CommunityCares_Web.Models.Assylum

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Assylum</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nit" class="control-label"></label>
                <input asp-for="Nit" class="form-control" />
                <span asp-validation-for="Nit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RepresentativeName" class="control-label"></label>
                <input asp-for="RepresentativeName" class="form-control" />
                <span asp-validation-for="RepresentativeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BussinessEmail" class="control-label"></label>
                <input asp-for="BussinessEmail" class="form-control" />
                <span asp-validation-for="BussinessEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CellphoneNumber" class="control-label"></label>
                <input asp-for="CellphoneNumber" class="form-control" />
                <span asp-validation-for="CellphoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>

            <div class="form-group" hidden>
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" id="Latitude" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" id="Longitude" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" value="1" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>

                <select asp-for="Region" class="control-label">
                    <option value="Cochabamba">Cochabamba</option>
                    <option value="Quillacollo">Quillacollo</option>
                    <option value="Sacaba">Sacaba</option>
                    <option value="Tiquipaya">Tiquipaya</option>
                    <option value="Colcapirhua">Colcapirhua</option>
                    <option value="Vinto">Vinto </option>
                    <option value="Sipe Sipe">Sipe Sipe </option>
                </select>
            </div>
            <br />
            <div id="map"></div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}
<script src="https://cdn.jsdelivr.net/npm/leaflet@1.7.1/dist/leaflet.js"></script>
<script>
    var mapa;
    var marcador;

    function initMap() {
        mapa = L.map('map').setView([-17.3866329, -66.2418649], 6);

        L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
            maxZoom: 18,
        }).addTo(mapa);

        marcador = L.marker([-17.3866329, -66.2418649], { draggable: true, opacity: 0 }).addTo(mapa);

        var primerDblClick = true;

        mapa.on('dblclick', function (e) {
            var latitud = e.latlng.lat;
            var longitud = e.latlng.lng;
            document.getElementById("Latitude").value = latitud;
            document.getElementById("Longitude").value = longitud;

            if (primerDblClick) {
                marcador.setLatLng([latitud, longitud]);
                marcador.setOpacity(1);
                primerDblClick = false;
            } else {
                marcador.setLatLng([latitud, longitud]);
            }
        });
    }
</script>

<script>
    window.onload = function () {
        initMap();
    };
</script>

CommunityCares_Web/Views/Assylum/Delete.cshtml
@model CommunityCares_Web.Models.Assylum

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Assylum</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RepresentativeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RepresentativeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BussinessEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BussinessEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CellphoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CellphoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

CommunityCares_Web/Views/Assylum/Details.cshtml
@model CommunityCares_Web.Models.Assylum

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Assylum</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nit)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nit)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RepresentativeName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RepresentativeName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BussinessEmail)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BussinessEmail)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CellphoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CellphoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Latitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Latitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Longitude)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Longitude)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegisterDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RegisterDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Region)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Region)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

CommunityCares_Web/Views/Assylum/Edit.cshtml
@model CommunityCares_Web.Models.Assylum

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Assylum</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nit" class="control-label"></label>
                <input asp-for="Nit" class="form-control" />
                <span asp-validation-for="Nit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RepresentativeName" class="control-label"></label>
                <input asp-for="RepresentativeName" class="form-control" />
                <span asp-validation-for="RepresentativeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BussinessEmail" class="control-label"></label>
                <input asp-for="BussinessEmail" class="form-control" />
                <span asp-validation-for="BussinessEmail" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CellphoneNumber" class="control-label"></label>
                <input asp-for="CellphoneNumber" class="form-control" />
                <span asp-validation-for="CellphoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Latitude" class="control-label"></label>
                <input asp-for="Latitude" class="form-control" />
                <span asp-validation-for="Latitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Longitude" class="control-label"></label>
                <input asp-for="Longitude" class="form-control" />
                <span asp-validation-for="Longitude" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RegisterDate" class="control-label"></label>
                <input asp-for="RegisterDate" class="form-control" />
                <span asp-validation-for="RegisterDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Region" class="control-label"></label>
                <input asp-for="Region" class="form-control" />
                <span asp-validation-for="Region" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CommunityCares_Web/Views/Assylum/Index.cshtml
@model IEnumerable<CommunityCares_Web.Models.Assylum>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nit)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RepresentativeName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BussinessEmail)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CellphoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Latitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Longitude)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegisterDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Region)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nit)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RepresentativeName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BussinessEmail)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CellphoneNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Address)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Latitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Longitude)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.RegisterDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Region)
                </td>
                <td>
                    <a asp-action="Create" asp-controller="Campaign" asp-route-id="@item.Id">Crear Campaña</a> |
                    <a asp-action="Index" asp-controller="Campaign" asp-route-id="@item.Id">Ver Campañas</a>
                </td>
            </tr>
        }
    </tbody>
</table>